version: '3'

services:

  app:
    build: ./.docker/php/
    container_name: app
    volumes:
      - ./src/:/var/www/
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: always
    ports:
      - "3306"
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379

  nginx:
    build: ./.docker/nginx/
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
